version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # We'll create this
      args:
        - VITE_API_URL=http://localhost:3000
        - VITE_WS_URL=ws://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev  # We'll create this
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=dev_password
      - DB_NAME=kahoot_clone
      - DB_PORT=5432
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=kahoot_clone
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: