entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "loferreira.nuno@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public
    watch: true

api:
  dashboard: true
  insecure: false

log:
  level: DEBUG
  format: json

http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    
  routers:
    frontend:
      rule: "Host(`crititag.com`)"
      entryPoints:
        - websecure
      service: frontend
      tls: 
        certResolver: letsencrypt
      middlewares:
        - https-redirect
    api:
      rule: "Host(`api.crititag.com`)"
      entryPoints:
        - websecure
      service: api
      tls:
        certResolver: letsencrypt
      middlewares:
        - https-redirect