entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "loferreira.nuno@gmail.com"  # IMPORTANT: Replace this with your real email
      storage: "/etc/traefik/acme.json"
      tlsChallenge: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-public

api:
  dashboard: true
  insecure: false  # Securing the dashboard

log:
  level: DEBUG

tls:
  certificates:
    - certFile: "/etc/traefik/acme.json"
      keyFile: "/etc/traefik/acme.json"

http:
  routers:
    frontend:
      rule: "Host(`crititag.com`)"
      entryPoints:
        - websecure
      service: frontend
      tls:
        certResolver: letsencrypt